### ISSUE TITLE
Wrong author

### ISSUE THREAD

**Issue by ieguiguren** [pgaref/HTTP_Request_Randomizer#38]
Hi

Samair.ru and rebro.weebly.com parsers were developed by me. Even if you separete it by modules (which I agree with), I'd should appear as author.

Commits:
b585c5db3749c540d371b4286233725a3f41b7a8 @ieguiguren added samair.ru to web parsers
83cebd56ceac7af18440181a180ee4b39dfc0bfd @ieguiguren added samair parsing
70f1602552308bef1f0877b4be6f32aa0a8339fe @ieguiguren added http://rebro.weebly.com/proxy-list.html

**Comment by pgaref** [comment]
Hello @ieguiguren 

I remember your contributions as you were one of the first project commiters :) 
As you mentioned the only reason the author name in the file is different is because I had to refactor the project at some point.

I would be more than happy to create a separate **CONTRIBUTORS** file to list the specific contibutions of each member (as they do in several open source projects). Would that make sense?

Cheers,
Panagiotis

**Comment by ieguiguren** [comment]
Hey!!

Nice to hearing from you so soon. Yes, makes perfect sense. Thanks

Cheers,
Ivan
